### ISSUE TITLE
Unable to get block timers

### ISSUE THREAD

**Issue by Michaltyk2** [PopSlime/CustomNPCs-Blockly#5]
## Description
Cannot put variable block `event.block` (from `BlockEvent$InteractEvent`) as argument of block `.getTimers()` (from `IBlockScripted`).
## Expected behavior
Fixed inserting argument to get generated code:
```js
event.block.getTimers()
```

**Comment by PopSlime** [comment]
## Confirmed
Nice catch. For some reason the `block` field of `BlockEvent` is type of `IBlock` instead of `IBlockScripted`, which causes the type checking system to reject the connection.

I will explore a way to solve it.
